allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@typescript-eslint/project-service@8.62.0'
  - '@typescript-eslint/scope-manager@8.62.0'
  - '@typescript-eslint/tsconfig-utils@8.62.0'
  - '@typescript-eslint/types@8.62.0'
  - '@typescript-eslint/typescript-estree@8.62.0'
  - '@typescript-eslint/utils@8.62.0'
  - '@typescript-eslint/visitor-keys@8.62.0'
  - globals@17.7.0
  - typescript-eslint@8.62.0

overrides:
  # Fix for:
  # Different instances of plugin "@typescript-eslint" found in multiple configs:
  #   UserConfig[0][3] > typescript-eslint/base, nuxt/typescript/setup.
  eslint-plugin-vue: $eslint-plugin-vue
  "@typescript-eslint/eslint-plugin": "^8.60.1"
  "@typescript-eslint/parser": "^8.60.1"
