allowBuilds:
  esbuild: true
  unrs-resolver: true
  vue-demi: true

overrides:
  # Fix for:
  # Different instances of plugin "@typescript-eslint" found in multiple configs:
  #   UserConfig[0][3] > typescript-eslint/base, nuxt/typescript/setup.
  eslint-plugin-vue: $eslint-plugin-vue
  "@typescript-eslint/eslint-plugin": "^8.60.1"
  "@typescript-eslint/parser": "^8.60.1"
